packages:
  - 'apps/*'
  - 'games/*'

overrides:
  diff: ^8.0.3
  esbuild: '>=0.25.0'
  shell-quote: 1.10.0
  'nanoid@<5': 3.3.18

allowBuilds:
  better-sqlite3: true
  esbuild: true

minimumReleaseAgeExclude:
  - '@vue/language-core@3.3.2'
  - vue-tsc@3.3.2
